-- MySQL Script generated by MySQL Workbench
-- Sat Apr  1 10:29:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS survey DEFAULT CHARACTER SET utf8 ;
USE survey ;

-- -----------------------------------------------------
-- Table survey.user
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS survey.user (
  username VARCHAR(16) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(32) NOT NULL,
  status TINYINT NOT NULL,
  iduser INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (iduser),
  UNIQUE INDEX username_UNIQUE (username),
  UNIQUE INDEX email_UNIQUE (email)
);


-- -----------------------------------------------------
-- Table survey.local
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS survey.local (
  idlocal INT NOT NULL AUTO_INCREMENT,
  local VARCHAR(50) NOT NULL,
  address VARCHAR(100) NOT NULL,
  url VARCHAR(2048) CHARACTER SET 'armscii8' NULL,
  PRIMARY KEY (idlocal))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table survey.department
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS survey.department (
  iddepartment INT NOT NULL AUTO_INCREMENT,
  department VARCHAR(20) NOT NULL,
  description VARCHAR(45) NULL,
  local_idlocal INT NOT NULL,
  PRIMARY KEY (iddepartment),
  INDEX fk_department_local_idx (local_idlocal),
  CONSTRAINT fk_department_local
    FOREIGN KEY (local_idlocal)
    REFERENCES survey.local (idlocal)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table survey.survey
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS survey.survey (
  idsurvey INT NOT NULL AUTO_INCREMENT,
  department_iddepartment INT NOT NULL,
  score INT NOT NULL,
  PRIMARY KEY (idsurvey),
  INDEX fk_survey_department1_idx (department_iddepartment),
  CONSTRAINT fk_survey_department1
    FOREIGN KEY (department_iddepartment)
    REFERENCES survey.department (iddepartment)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE survey;

ALTER TABLE survey ADD COLUMN createdat DATETIME DEFAULT NOW();

ALTER TABLE survey ADD COLUMN updatedat DATETIME DEFAULT NOW();

INSERT INTO local(local, address, url) VALUES ('Cidade do saber','Rua do Telegrafo, S/Nº, bairro do Natal, Camaçari-BA','https://secult.camacari.ba.gov.br/?page_id=532%27');
INSERT INTO local(local, address, url) VALUES ('Teatro Alberto Martins','Rua Eixo Urbano Central S/Nº, Centro, Camaçari-BA','https://secult.camacari.ba.gov.br/?page_id=537%27');
INSERT INTO local(local, address, url) VALUES ('Biblioteca Jorge Amado','Rua do Telégrafo, S/Nº, 1º andar, Cidade do Saber, bairro do Natal,','https://secult.camacari.ba.gov.br/?page_id=1171%27');
INSERT INTO local(local, address, url) VALUES ('Museu de Camassary','Avenida Eixo Urbano Central, S/Nº, Centro, Camaçari-BA, antiga Estação de Trem','https://secult.camacari.ba.gov.br/?page_id=1552%27');
INSERT INTO local(local, address, url) VALUES ('Biblioteca Infantojuvenil','Rua Santa Bernadete, Praça Abrantes, nº 47, Centro, Camaçari-BA, 42800-010','https://secult.camacari.ba.gov.br/?page_id=1035%27');

INSERT INTO `department`(`department`, `description`, `local_idlocal`) VALUES ('NOC','Nucleo de Orientação Cultural',1);
INSERT INTO `department`(`department`, `description`, `local_idlocal`) VALUES ('NOC','Nucleo de Orientação Cultural',2);
INSERT INTO `department`(`department`, `description`, `local_idlocal`) VALUES ('NOC','Nucleo de Orientação Cultural',3);
INSERT INTO `department`(`department`, `description`, `local_idlocal`) VALUES ('NOC','Nucleo de Orientação Cultural',4);
INSERT INTO `department`(`department`, `description`, `local_idlocal`) VALUES ('NOC','Nucleo de Orientação Cultural',5);

INSERT INTO `survey`(`department_iddepartment`, `score`) VALUES (1,5);
INSERT INTO `survey`(`department_iddepartment`, `score`) VALUES (1,1);
INSERT INTO `survey`(`department_iddepartment`, `score`) VALUES (3,5);
INSERT INTO `survey`(`department_iddepartment`, `score`) VALUES (2,3);
INSERT INTO `survey`(`department_iddepartment`, `score`) VALUES (5,5);
INSERT INTO `survey`(`department_iddepartment`, `score`) VALUES (5,2);